### ISSUE TITLE
Gift aid option

### ISSUE THREAD

**Issue by yousafali8384** [Studio164a/crowdfunding#13]
Hello Support team
Am using your extension and i loved it great job . i have purchased Unity crowdfunding theme from themeforest and i am in a small issue . I want to add the Gift aid option in Campaign checkout page so that UK tax payers can Reclaim for the Gift Aid .
I don't how to do it i know there should be small modification in code 
Sorry if i am posting here i know its not a place to ask for such a issue but i need it can you please guide me or suggest any plugin or modification code.
Thanks in advance

**Comment by ericnicolaas** [comment]
Sorry, but we no longer actively support or develop this plugin.
