### ISSUE TITLE
Translation file not working

### ISSUE THREAD

**Issue by JustinasI** [Studio164a/crowdfunding#14]
I've translated plugin to Lithuanian language, but translation isn't appearing. I don't know what to do. Even if I change template file, translation isn't appearing....

**Comment by allmindmaps** [comment]
Me too, not all labels could translated. Label that directly included in html doesn't rendered, e.g:

`<label for="rewards[<?php echo esc_attr( $k ); ?>][name]"><?php _e( 'Reward', 'atcf' ); ?></label>`

**Comment by ericnicolaas** [comment]
@JustinasI and @allmindmaps: We're no longer supporting this plugin or developing it at all, so I'm afraid I can't be of much help here. If you're looking for a solution with ongoing support, check out our plugin Charitable: https://www.wpcharitable.com
